apiVersion: v1
kind: Service
metadata:
  name: autopus
  labels:
    app: autopus
spec:
  type: ClusterIP
  selector:
    app: autopus
  ports:
    - name: gateway
      port: 18789
      targetPort: 18789
      protocol: TCP
