export { createBrowserTool } from "./src/browser-tool.js";
export {
  applyBrowserProxyPaths,
  browserAct,
  browserArmDialog,
  browserArmFileChooser,
  type BrowserBridge,
  browserCloseTab,
  browserConsoleMessages,
  browserCreateProfile,
  type BrowserCreateProfileResult,
  browserDeleteProfile,
  type BrowserDeleteProfileResult,
  browserDoctor,
  type BrowserDoctorCheck,
  type BrowserDoctorReport,
  type BrowserExecutable,
  browserFocusTab,
  type BrowserFormField,
  browserNavigate,
  browserOpenTab,
  browserPdfSave,
  browserProfiles,
  browserResetProfile,
  type BrowserResetProfileResult,
  type BrowserRouteRegistrar,
  browserScreenshotAction,
  type BrowserServerState,
  browserSnapshot,
  browserStart,
  browserStatus,
  type BrowserStatus,
  browserStop,
  type BrowserTab,
  browserTabAction,
  browserTabs,
  type BrowserTransport,
  closeTrackedBrowserTabsForSessions,
  createBrowserControlContext,
  createBrowserRouteContext,
  createBrowserRouteDispatcher,
  createBrowserRuntimeState,
  DEFAULT_AI_SNAPSHOT_MAX_CHARS,
  DEFAULT_BROWSER_EVALUATE_ENABLED,
  DEFAULT_AUTOPUS_BROWSER_COLOR,
  DEFAULT_AUTOPUS_BROWSER_PROFILE_NAME,
  DEFAULT_UPLOAD_DIR,
  ensureBrowserControlAuth,
  getBrowserControlState,
  getBrowserProfileCapabilities,
  installBrowserAuthMiddleware,
  installBrowserCommonMiddleware,
  isPersistentBrowserProfileMutation,
  movePathToTrash,
  normalizeBrowserFormField,
  normalizeBrowserFormFieldValue,
  normalizeBrowserRequestPath,
  parseBrowserMajorVersion,
  persistBrowserProxyFiles,
  type ProfileStatus,
  readBrowserVersion,
  redactCdpUrl,
  registerBrowserRoutes,
  resolveBrowserConfig,
  resolveBrowserControlAuth,
  type ResolvedBrowserConfig,
  type ResolvedBrowserProfile,
  resolveExistingPathsWithinRoot,
  resolveGoogleChromeExecutableForPlatform,
  resolveProfile,
  resolveRequestedBrowserProfile,
  runBrowserProxyCommand,
  type SnapshotResult,
  startBrowserBridgeServer,
  startBrowserControlServiceFromConfig,
  stopBrowserBridgeServer,
  stopBrowserControlService,
  stopBrowserRuntime,
  trackSessionBrowserTab,
  untrackSessionBrowserTab,
} from "./src/browser-runtime.js";
export { registerBrowserCli } from "./src/cli/browser-cli.js";
export { createBrowserPluginService } from "./src/plugin-service.js";
export { handleBrowserGatewayRequest } from "./src/gateway/browser-request.js";
export { browserHandlers } from "./src/gateway/browser-request.js";
export {
  definePluginEntry,
  type AutopusPluginApi,
  type AutopusPluginToolContext,
  type AutopusPluginToolFactory,
} from "autopus/plugin-sdk/plugin-entry";
