export const browserCoreExamples = [
  "autopus browser status",
  "autopus browser start",
  "autopus browser start --headless",
  "autopus browser stop",
  "autopus browser tabs",
  "autopus browser open https://example.com",
  "autopus browser focus abcd1234",
  "autopus browser close abcd1234",
  "autopus browser screenshot",
  "autopus browser screenshot --full-page",
  "autopus browser screenshot --ref 12",
  "autopus browser snapshot",
  "autopus browser snapshot --format aria --limit 200",
  "autopus browser snapshot --efficient",
  "autopus browser snapshot --labels",
];

export const browserActionExamples = [
  "autopus browser navigate https://example.com",
  "autopus browser resize 1280 720",
  "autopus browser click 12 --double",
  "autopus browser click-coords 120 340",
  'autopus browser type 23 "hello" --submit',
  "autopus browser press Enter",
  "autopus browser hover 44",
  "autopus browser drag 10 11",
  "autopus browser select 9 OptionA OptionB",
  "autopus browser upload /tmp/autopus/uploads/file.pdf",
  'autopus browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "autopus browser dialog --accept",
  'autopus browser wait --text "Done"',
  "autopus browser evaluate --fn '(el) => el.textContent' --ref 7",
  "autopus browser console --level error",
  "autopus browser pdf",
];
